name: me_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed_annotation: ^3.1.0
  flutter_gen_runner: ^5.12.0
  freezed: ^3.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

