name: me_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.2
  go_router: ^17.0.0
  supabase_flutter: ^2.5.6
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  freezed_annotation: ^3.1.0
  flutter_gen_runner: ^5.12.0
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - .env

